### ISSUE TITLE
Likes not working for remote posts

### ISSUE THREAD

**Issue by debecerra** [CMPUT404F21TEAM/social-distribution#161]
When a user likes an InboxPost, we need to make an API call to their host server to like the post. Right now, we depend on Django ORM which only works for a local post, so this needs to be changed.

**Comment by olivier-vadiaval** [comment]
Basically, we have to make a request to the following endpoint, if I understand correctly.

- URL: ://service/author/{author_id}/post/{post_id}/likes
    - GET a list of likes from other authors on author_id’s post post_id

How should we handle errors? Should we avoid displaying the whole post, or display the post without the likes but have some kind of Toast indicating that the likes couldn't be loaded?

**Comment by debecerra** [comment]
I like the idea of having a toast, but that would be a "nice to have" and not a "must-have" so we should leave it to the end. For now, I think it would be good to display the post without the likes, maybe just replace the like text with some sort of error message.

I think the second option would be better. Doesn't make a lot of sense to not display the post if there are no issues with the post itself.

**Comment by olivier-vadiaval** [comment]
That sounds good 👌 Thank you
