### ISSUE TITLE
Allow /app/post endpoint to display both local and remote posts

### ISSUE THREAD

**Issue by debecerra** [CMPUT404F21TEAM/social-distribution#174]
Should probably only display InboxPosts. I think it only displays LocalPosts right now, meaning it won't work for remote posts

**Comment by debecerra** [comment]
#176

**Comment by olivier-vadiaval** [comment]
Is it the app/post endpoint or the app/home endpoint?

**Comment by debecerra** [comment]
Sorry, the title should have said "remote" instead of "private". 

I think this would apply to just to any posts viewed through the Inbox tab, or posts viewed on the single post page that lets you comment on the post too.

Sorry for the late reply.
