### ISSUE TITLE
Finish all remaining API endpoints

### ISSUE THREAD

**Issue by debecerra** [CMPUT404F21TEAM/social-distribution#175]
Leave as NotImplementedError if not ready or nontrivial to implement.

**Comment by debecerra** [comment]
T11 let us know that we're missing the single comments API endpoint

**Comment by tylerelston** [comment]
Missing:
- #208  
- #207
- #206 
- #205

**Comment by tylerelston** [comment]
Closing this to be replaced with the above issues
