### ISSUE TITLE
Inbox posts link to the wrong post

### ISSUE THREAD

**Issue by tylerelston** [CMPUT404F21TEAM/social-distribution#176]
1. Account 1 makes a PUBLIC post
2. Account 1 and account 2 become FRIENDS (both follow and accept)
2. Account 1 makes a PUBLIC post (sent to Account 2's stream)

At this point, if account 2 goes to their inbox, they see the correct post, but if they click comments, they are directed to post 1.

If Account 1 deletes post 1, Account 2's inbox returns an error: `LocalPost matching query does not exist.`

**Comment by debecerra** [comment]
This most likely stems from rendering LocalPosts on the user interfaces instead of InboxPosts. If we only render InboxPosts, most of these issues should be fixed since all IDs will reference the same model.

**Comment by debecerra** [comment]
Closed by #202
