### ISSUE TITLE
AJAX requests being made on non-ajax page

### ISSUE THREAD

**Issue by debecerra** [CMPUT404F21TEAM/social-distribution#284]
Noticed that AJAX requests were being sent out unnecessarily on the /profile page.

@olivier-vadiaval could you take a look? Would be good if we could avoid this since the Heroku server is very fragile and can't handle too many requests.

**Comment by olivier-vadiaval** [comment]
Ohh I think I know why. I'll fix it right put up a pr with some more fixes related to ajax.

**Comment by olivier-vadiaval** [comment]
Thank you!
