### ISSUE TITLE
43 - As an author, I want to be able to make posts that are unlisted, that are publicly shareable by URI alone (or for embedding images)

### ISSUE THREAD

**Issue by debecerra** [CMPUT404F21TEAM/social-distribution#36]
Unlisted posts can still be shared, and their image links can still be embedded via markdown in other posts
* make a GET request again the unlisted post URL, obtain that image, and display it 

From Jawad: 
The unlisted posts links that are shared should be publicly accessible but I think the link copied is only for authenticated users. Can you please verify? If it is only for logged in users may need a view which can be accessed by all users like the login/sign up page.
* Make new view (instead of comments view) which can be accessed without logging in 
* Decide if logged in users see comments view or this new view (whichever is easier)

**Comment by JawadHossain** [comment]
I think we should not show the copy link button on inbox posts.
